[package]
name = "scale"
version = "0.1.0"
edition = "2024"

[dependencies]
menu = { git = "https://github.com/rileyhernandez/menu.git"}
thiserror = "2.0.12"
time = "0.3.41"
reqwest = "0.12.22"
serde_json = "1.0.140"
phidget = "0.4.0"
log = "0.4.27"